Create pyladies-soflo.json
cosimameyer/awesome-pyladies-blogs pull request #44
Opened 2023-10-06 15:35 UTC by aerikpawson

Adding to this list PyLadies SoFlo YouTube channel.
cc @InessaPawson

2023-10-07 05:08 UTC, cosimameyer requested changes
Thanks so much for reaching out and submitting the entry, @aerikpawson 🥳 
Just a few small changes are needed and we're good to go 😊

@InessaPawson can you also confirm that you're OK with adding your data to the repo? It'll be also used to promote your chapter's material on Mastodon with the [PyLadies bot](https://botsin.space/@pyladies_bot).

2023-10-07 05:08 UTC, cosimameyer commented on blogs/pyladies-soflo.json
> +  "type": "YouTube channel",
`type` should be `"type": "youtube"` so that the algorithm captures it correctly :)

2023-10-07 05:08 UTC, cosimameyer commented on blogs/pyladies-soflo.json
> +         "linkedin": "ipawson"
LinkedIn requires here a trailing `/`, so it should be `"linkedin": "ipawson/"`

2023-10-07 05:08 UTC, cosimameyer commented on blogs/pyladies-soflo.json
> +         "github": "inessapawson",
I believe the correct GitHub handle is `InessaPawson`, so it should be `"github": "InessaPawson"`

2023-10-08 02:48 UTC, aerikpawson commented
@cosimameyer I've addressed all your comments in the second commit.

2023-10-08 02:53 UTC, InessaPawson commented
@cosimameyer Yes, I agree. 
Thank you for reaching out and promoting the PyLadies content!

2023-10-08 05:13 UTC, cosimameyer approved these changes

2023-10-08 05:14 UTC, cosimameyer commented
Amazing, thank you for contributing! 🙌

2023-10-08 05:15 UTC, merged